<?php

namespace App\Filament\Admin\Resources;

use App\Filament\Admin\Resources\ReportResource\Pages;
use App\Models\Report;
use App\Traits\HasTranslatedLabels;
use Filament\Forms;
use Filament\Forms\Components\Hidden;
use Filament\Forms\Form;
use Filament\Resources\Resource;
use Filament\Tables;
use Filament\Tables\Columns\TextColumn;
use Filament\Tables\Table;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Model;


class ReportResource extends Resource
{
    protected static ?string $navigationIcon = 'tabler-message-report';

    protected static ?int $navigationSort = 2;

    public static function table(Table $table): Table
    {
        return $table
            ->columns([
                TextColumn::make('title')
                    ->label('Title')
                    ->translateLabel()
                    ->sortable()
                    ->searchable()
                    ->limit(50),

                TextColumn::make('content')
                    ->label('Content')
                    ->translateLabel()
                    ->limit(100)
                    ->wrap(),

                TextColumn::make('sportFederation.name')
                    ->label('Sport Federation')
                    ->translateLabel()
                    ->sortable()
                    ->searchable()
                    ->badge(),
            ])
            ->actions([
                Tables\Actions\ViewAction::make()
            ]);
    }

    public static function form(Form $form): Form
    {
        return $form
            ->schema([
                Forms\Components\Fieldset::make()
                    ->schema([
                        Forms\Components\TextInput::make('title')
                            ->label('Title')
                            ->translateLabel()
                            ->required(),

                        Forms\Components\Textarea::make('content')
                            ->label('Content')
                            ->translateLabel()
                            ->required(),

                        Hidden::make('sport_federation_id')
                            ->default(auth()->user()->sport_federation_id),

                    ])->columns(1)
            ]);
    }




















    use HasTranslatedLabels;

    protected static ?string $model = Report::class;

    public static function getPages(): array
    {
        return [
            'index' => Pages\ListReports::route('/'),
            'create' => Pages\CreateReport::route('/create'),
            'edit' => Pages\EditReport::route('/{record}/edit'),
        ];
    }

    public static function canEdit(Model $record): bool
    {
        return false;
    }

    public static function canCreate(): bool
    {
        return false;
    }

    public static function getEloquentQuery(): Builder
    {
        return parent::getEloquentQuery()->whereNull('club_id'); // TODO: Change the autogenerated stub
    }

}
